### ISSUE TITLE
remove_ban.py usage: "AttributeError: 'module' object has no attribute 'g_banlist'" 

### ISSUE THREAD

**Issue by NeutralKaon** [BinaryDefense/artillery#109]
Hi there, 

Thanks again for making this excellent tool. 

Am I right in thinking that to remove a blacklisted IP, the "correct" thing to do is just call `sudo /var/artillery/remove_ban.py <ip address>`? If so, on Ubuntu 18.04, I get: 

```
$ sudo /var/artillery/remove_ban.py 10.x.x.x
Traceback (most recent call last):
  File "/var/artillery/remove_ban.py", line 12, in <module>
    path = check_banlist_path()
  File "/var/artillery/src/core.py", line 522, in check_banlist_path
    if os.path.isfile(globals.g_banlist):
AttributeError: 'module' object has no attribute 'g_banlist'
```

Also -- is there documentation and a wiki anywhere for this?

**Comment by russhaun** [comment]
hey just saw this. try this open removeban.py and insert init_globals() below imports. the global values are not being created.

like so.


import sys 
from src.core import *
init_globals()

try:
  rest of code

just place init function at end of imports and try again. lmk if it works

**Comment by russhaun** [comment]
as far as documentation there is a good overview of it at this link

https://adhdproject.github.io/#!Tools/Annoyance/Artillery.md#Example_1:_Running_Artillery

**Comment by NeutralKaon** [comment]
> hey just saw this. try this open removeban.py and insert init_globals() below imports. the global values are not being created.
> 
> like so.
> 
> import sys
> from src.core import *
> init_globals()
> 
> try:
> rest of code
> 
> just place init function at end of imports and try again. lmk if it works

Yep -- that fixed it, and it works, -- thank you!
