### ISSUE TITLE
harden.py

### ISSUE THREAD

**Issue by benichmt1** [BinaryDefense/artillery#11]
If the vision for harden.py is to be something completely filled out, what checks would be nice to be implemented? I have my own hardening script that I could easily adapt to this framework but just wanted to see to what depth it was intended to go.

Re: #10

**Comment by trustedsec** [comment]
Would love to continue to add to this - the vision was to build on that and maybe even a framework because harden.py that add more "modules" for checking in a specific format so you can get better. Only issue is making sure its cross dependent on different linux installations
