### ISSUE TITLE
Secondary config file

### ISSUE THREAD

**Issue by jberry** [BinaryDefense/artillery#12]
Any thoughts on creating/reading a secondary config file, so config can stay in GIT, but we can have a local config file with OUR values that doesn't keep getting overwritten by pulls/merges/etc?

I'm not quite sure how you'd implement it right now, since the core.py reads the exact config file when it needs a value.  Maybe change the read_config to read a hash, thats loaded earlier based on first reading config and then reading something like "user_config"?

Or just have all the possible config parameters in a single file, set default values inside the software, and tell the user to override the defaults in a user_config file or something?

**Comment by trustedsec** [comment]
That's a good idea. We can have a master file for new config values and maybe an updater if you want to merge those changes into an existing config. I'll work on it and add it to milestones. Thanks!
