### ISSUE TITLE
setup fails on Windows 2012

### ISSUE THREAD

**Issue by Reality9** [BinaryDefense/artillery#14]
Setup fails with this error:
Welcome to the Artillery installer. Artillery is a honeypot, file monitoring, an
d overall security tool used to protect your nix systems.

Written by: Dave Kennedy (ReL1K)

Do you want to install Artillery and have it automatically run when you restart
[y/n]: y
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    os.makedirs(program_files + "\\Artillery\\logs")
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C
:\\Program Files (x86)\\Artillery\\logs'

**Comment by Reality9** [comment]
I resolved this issue by reordering the shutil.copytree.
Although artillery never actually starts.

**Comment by trustedsec** [comment]
Working on Windows for next release, thanks for the report!

**Comment by C0deH4cker** [comment]
@trustedsec Where is the commit containing this fix? If the fix isn't yet pushed, then this issue shouldn't be closed so others who come across the same problem can find this issue. I fixed the setup.py script manually by reordering directory creation after the shutil line.

Also I see in issue comments you claim Windows support in some partial form, but you mention that it's a very manual process. Can you please document this process so users can run Artillery on Windows until the process is automated? I'm already running this on Linux; I'd like to test it out on Windows, but the complete lack of information makes this very difficult.

Thanks!

**Comment by trustedsec** [comment]
It's marked closed because we already mark Windows as experimental and not tested. There's a lot of work to be done here and well aware of it.

**Comment by C0deH4cker** [comment]
Where is Artillery marked as experimental and untested? In the README, Windows is listed as a supported platform right next to Linux without anything to distinguish the lack of support. If you provide instructions for Windows users to get up and running with Artillery, people such as myself may submit pull requests fleshing out Windows support, so it can actually be considered a supported platform. I appreciate the work you've put into this project, and I would love to see it be usable on Windows.

**Comment by russhaun** [comment]
only commenting because i see this is windows related. Basic support for windows is now there. it has been tested on win 7/8/10 so far.server support to come soon 2008?/2012/2016. would love comments on windows side to see what kind of features you would like to see. check out my repo for ideas already out there feel free to suggest more.
