### ISSUE TITLE
Error, Artillery was unable to log into the mail server

### ISSUE THREAD

**Issue by sec360dude** [BinaryDefense/artillery#16]
I've installed Artillery on Ubuntu 14.04.3 LTS (GNU/Linux 3.16.0-30-generic x86_64).
The install completed OK and folder was create in /var/artillery.
I've changed the config file to allow for email alerts, but getting this error in syslog:
 Error, Artillery was unable to log into the mail server
I can send emails via the relay using Telnet.
Am I missing something, please help

# SHOULD EMAIL ALERTS BE SENT
EMAIL_ALERTS="ON"
#
# CURRENT SUPPORT IS FOR SMTP, ENTER YOUR USERNAME AND PASSWORD HERE. LEAVE BLANK FOR OPEN RELAY
SMTP_USERNAME=""
#
# ENTER THE SMTP PASSWORD HERE. LEAVE BLANK FOR OPEN RELAY
SMTP_PASSWORD=""
#
# THIS IS WHO TO SEND THE ALERTS TO - EMAILS WILL BE SENT FROM ARTILLERY TO THIS ADDRESS
ALERT_USER_EMAIL="myemail@mydomain.com"
#
# FOR SMTP ONLY HERE, THIS IS THE MAILTO
SMTP_FROM="mailrelayUser@mydomain.com"
#
# SMTP ADDRESS FOR SENDING EMAILS, DEFAULT IS GMAIL
SMTP_ADDRESS="192.168.x.x"
#
# SMTP PORT FOR SENDING EMAILS DEFAULT IS GMAIL WITH TTLS
SMTP_PORT="25"
#
# THIS WILL SEND EMAILS OUT DURING A CERTAIN FREQUENCY. IF THIS IS SET TO OFF, ALERTS
# WILL BE SENT AUTOMATICALLY AS THEY HAPPEN (CAN LEAD TO A LOT OF SPAM)
EMAIL_TIMER="OFF"
#
# HOW OFTEN DO YOU WANT TO SEND EMAIL ALERTS (DEFAULT 10 MINUTES)
EMAIL_FREQUENCY="600"

**Comment by nskousen** [comment]
I'm having issues also with the mailer functions.   (See issue #72) on github/trustedsec/artillery   mail from a cron job works fine, but Artillery cant log into mail server with same url and credentials.   During the SSMPT setup I had to add a config lines  useSTARTTLS=YES and AuthLogin=YES to get the errors tamed, but crontab mails fine now - just cant get Artillery to send emails...    Niel ( nskousen@ecsecurityinc.com )

**Comment by BigfootDmnt** [comment]
I cant make it send email with SMTP either. Tried Ubuntu and CentOS, local smtp and windows server - all give "Artillery was unable to log into the mail server"

**Comment by nskousen** [comment]
I ended up building a little script (alerts.sh) that does tail /var/artillery/logs/alerts.log > tailA.  Then it  Diff's the last tail and if the diff isn't null it sends mail.    I then have a 5min Cron to run it.    Same as the artillery config for mail aggregated for 5min...   Works fine

Niel

**Comment by jroudabush14** [comment]
Hello Niel, 
Is there anyway that you could share that script with everyone? i'm having the same issue when I configured artillery on my raspberry pi 2 for school Project.

Josh

**Comment by nskousen** [comment]
sure, its pretty ratty, but your welcome to it...  It builds a little text file and sends it.   tailA, tailB, and tailC are a rotating set of text files for the diff.    I'm sure most of you could do better...   Niel

cron entry:   
#  5 min  check alert.log and if changed, send email alert
*/5 * * * * .  /root/alert.sh  

alerts.sh:
$ nano alerts.sh		: Build alert.sh since Artillery email doesn’t work well
#!/bin/sh
#
cp tailB tailC					: roll down, over-write tailC
cp tailA tailB
tail /var/artillery/logs/alerts.log > tailA		: new tailA
diff tailA tailB > tailDiff				: save 
if  [ -s tailDiff ] then				:  if diff not null, build alert.txt and mail to me
	echo –n Host:  >> alert.txt
hostname  >> alert.txt
echo –n Addr:  >> alert.txt
hostname –I  >> alert.txt
echo  >> alert.txt
echo –n Time:  >> alert.txt
date  >> alert.txt
vcgencmd measure_temp  >> alert.txt
echo  >> alert.txt
free –m  >> alert.txt
echo  >> alert.txt
echo >> alert.txt
echo “Artillery Alert Log file extract:”  >> alert.txt
tail /var/artillery/logs/alerts.log  >> alert.txt
mail –s “Artillery Alert: Artillery name"  nskousen@example.net < alert.txt
echo

**Comment by jroudabush14** [comment]
Great thank you for sharing

**Comment by trustedsec** [comment]
I'm looking into it to see whats happening - we also accept pull requests if you find the fix.

**Comment by trustedsec** [comment]
Just pushed the fix out to the latest version. Thanks for the report!

**Comment by hutchingsp** [comment]
OK now I see this which is a bit different:

Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] 2016-08-01 00:29:23: Error, Artillery was unable to log into the mail server
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian [!] Printing error: 'LazyImporter' object is not callable
Aug  1 00:29:23 debian 2016-08-01 00:29:23.360228 [!] Artillery has detected an attack from IP address: 192.168.1.64 for a connection on a honeypot port: 445

The LazyImporter stuff wasn't being logged previously.

Section from config, 

# THIS IS WHO TO SEND THE ALERTS TO - EMAILS WILL BE SENT FROM ARTILLERY TO THIS ADDRESS
ALERT_USER_EMAIL="my at gmail.com"
#
# FOR SMTP ONLY HERE, THIS IS THE MAILTO
SMTP_FROM="Artillery Incident"
#
# SMTP ADDRESS FOR SENDING EMAILS, DEFAULT IS GMAIL
SMTP_ADDRESS="localhost"
#
# SMTP PORT FOR SENDING EMAILS DEFAULT IS GMAIL WITH TTLS
SMTP_PORT="25"
