### ISSUE TITLE
Unable to turn off threat intelligence feed

### ISSUE THREAD

**Issue by natv** [BinaryDefense/artillery#17]
Hello,

Perhaps I'm misunderstanding the settings.

I'm wanting to populate banlist.txt with **ONLY the IPs that are hitting this actual box.**

I set the following setting to OFF in an attempt to stop artillery from auto-populating the banlist.txt file:

THREAT_INTELLIGENCE_FEED="OFF"

I then cleared the banlist.txt file, but it is still getting populated with the IPs at https://www.binarydefense.com/banlist.txt

Thanks for any help with this.

**Comment by trustedsec** [comment]
Unfortunately I'm unable to reproduce this one. When intelligence feeds are set to OFF, it does not go into that function however if SOURCE_FEEDS are ON it will pull other feeds in. May need to shut that one off. I changed the code to check to see if intelligence_feeds are on/off, if they are off they won't pull intelligence feeds for source feeds.
