### ISSUE TITLE
Setup.py Issue

### ISSUE THREAD

**Issue by mastenp** [BinaryDefense/artillery#20]
FYI I posted this on the old thread by mistake.  

I am trying to install this on a digitalocean droplet and receive the below error when running the setup.py.

Traceback (most recent call last):
File "./setup.py", line 10, in 
from src.core import *
File "/root/artillery/src/core.py", line 422
if not os.path.isdir("/var/artillery/logs"): os.makedirs("/var/artillery/logs")
^
TabError: inconsistent use of tabs and spaces in indentation

I am running Python 3.5.2

**Comment by trustedsec** [comment]
thanks, ive fixed this one
