### ISSUE TITLE
Error, Artillery was unable to log into the mail server

### ISSUE THREAD

**Issue by hutchingsp** [BinaryDefense/artillery#21]
I just setup Artillery on a brand new Ubuntu and then Debian VM.

Install went fine, detection works but, but I just cannot get emails to fire, just get "Error, Artillery was unable to log into the mail server".

All I'm doing is editing config to point to localhost and I can see from the mail logs that when I trigger the honeypot it just isn't connecting.

I don't see anything in the install guide about any pre-reqs but I must be missing something obvious, though I've no clue what.

Can anyone help please?

**Comment by trustedsec** [comment]
Duplicate issue here: https://github.com/BinaryDefense/artillery/issues/16
