### ISSUE TITLE
Cant find project artillery logs 

### ISSUE THREAD

**Issue by joshbros** [BinaryDefense/artillery#22]
I recently downloaded Project Artillery to my Ubuntu server.  However, I dont see any syslog file that it is logging activity to.  Is artillery logging this activity to a different log file?  I have looked in /var/log/messages, but artillery is not logging activity to there.  When I look in /var/v
artillery, I dont see any "syslog" file.

[artillery.config.docx](https://github.com/BinaryDefense/artillery/files/394475/artillery.config.docx)

**Comment by trustedsec** [comment]
git pull the latest found a bug works now

**Comment by joshbros** [comment]
I still don't see the log file in the artillery directory.  Is that where it should be?
