### ISSUE TITLE
Bulk/Digest email report

### ISSUE THREAD

**Issue by aremai** [BinaryDefense/artillery#23]
Hi,

not really an issue, more of a feature request.
would it be possible to receive once a day a bulk/digest email report, instead of the single Artillery Incident mails?

If not, what are the reasons for it?

**Comment by trustedsec** [comment]
Mostly due to this being an open source tool that we put in our own time and effort to do. It's a matter of priority. We accept pull requests for the tool and many contribute. Feel free to add and submit your progress!
