### ISSUE TITLE
New Setup.py Issue

### ISSUE THREAD

**Issue by mastenp** [BinaryDefense/artillery#26]
Now that the Line 10 problem was fixed, now I get the below error when trying to run the setup.py

File "setup.py", line 94
    filewrite = file("/Library/LaunchDaemons/com.artillery.plist", "w")
                                                                      ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by trustedsec** [comment]
Looks like you are using an old version of Artillery here. Works fine on mine...
