### ISSUE TITLE
Artillery crash on Ubuntu 14.04

### ISSUE THREAD

**Issue by dlauer** [BinaryDefense/artillery#27]
Hi, I just installed Artillery on Ubuntu 14.04 (Python 2.7 running under Anaconda). It was running and adding a bunch of IPs to iptables, but then suddenly crashed after about 5 minutes with the following error:
artillery.py crashed with IOError in copyfile(): [Errno 2] No such file or directory: '/var/artillery/database/temp.database'

Not sure if I should touch the file or not, figured I'd report it just in case.

**Comment by dlauer** [comment]
Also, not sure why as the artillery.py process is using a huge amount of CPU, but a netstat -anp doesn't show it listening on any of the ports it's configured for.

**Comment by trustedsec** [comment]
I'm unable to reproduce this one on 14.04, all of the temp.database files have if os.isfile - so it should not copy if its not there..
