### ISSUE TITLE
IPtables doesn't open ports to allow connectivity to honeypot automatically

### ISSUE THREAD

**Issue by jberry** [BinaryDefense/artillery#3]
Should activating the honeypot automatically add the appropriate IPTables ACCEPT rules for any honeypot ports it successfully launched a listener on?  

Maybe add a new config option to AUTO_ACCEPT_HONEYPOT_PORTS or something, that adds them to the ARTILLERY chain. The ban inserts at line 1 always, so the accepts to the honeypot ports would get pushed further down the list so its still banning proper. And stopping artillery will delete that chain and close the ports back off automatically.

**Comment by trustedsec** [comment]
Closed due to fixing - thanks again!
