### ISSUE TITLE
Line 70

### ISSUE THREAD

**Issue by oldkingcone** [BinaryDefense/artillery#46]
This throws an error, for some reason on linux, and using python2.X, it may have worked for you on your systems but I had to remove the os.mkdirs in order to get it to run. its on line 70.

Other than that its working like a dream, i love it.

**Comment by russhaun** [comment]
hey whats up noticed your post and decided to comment. I fixed the issue you refer to in my repo. i also added some files to deal with line endings it works on linux and windows now and hopefully will end this issue(line endings). if you like please test and let me know if your issue still exits. pull request #45 and #43 also deal with this issue as well just waiting to get accepted the only difference between them and my repo is a .gitattributes file.

**Comment by russhaun** [comment]
on a side note. on linux when it asks you to update say no or it will overwrite changes that i applied and you will not see them as the fix has not been applied on the main BD repo

**Comment by oldkingcone** [comment]
Gotcha! Hey I was thinking of adding in an NMAP auto scan and submitting the code here, so if there is a bogus scan/connection attempt it would send back an NMAP scan automatically, as well as a few other active defense tactics.

**Comment by oldkingcone** [comment]
Or even adding in a Shodan Query, to geolocate as well as see which ports are opened on the machine.
