### ISSUE TITLE
exact step that a 7y old can do?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [BinaryDefense/artillery#47]
what are the exact steps from beginning to end to do this,

run ./setup.py 

on win10

what are

what are the exact steps from beginning to end to do this:

edit your /else/init.d/rc.local to start artillery on boot up

on win10

**Comment by russhaun** [comment]
on windows 10 you just need to doubleclick setup.py to begin. it will install to C:\Program Files(x86) there will be a directory called "artillery" open the directory and double click on a file called "artillery_start" this will launch artillery. you can copy that file to where you want to start it in the future. the second part about /etc/init.d/rc.local. that is a linux path and does not apply to windows.I would like to help but need more info.

**Comment by russhaun** [comment]
Just made a short video if that works better. here is the link https://youtu.be/nay_mgphJE4

**Comment by russhaun** [comment]
just wondering if  above posts were helpful in your situation. let me know if you need more info

**Comment by oldkingcone** [comment]
I know on most windows systems, you can add in an entry into the registry(regedit program) under the HKLM(inside your registery, it is name or should be name either HKEY_LOCAL_MACHINE, or on older versions of windows HKLM) -> software -> windows -> current version -> RUN, create a new STRING VALUE name it whatever you want, something descriptive at the very least, add inside that STRING VALUE, python C:\path\to\script for the main artillery script.

If you are unable to follow russhaun's advice or if that didn't work, you can always use this way to do it manually.

**Comment by russhaun** [comment]
just to comment on what oldkingcone said he is correct.here is the full path to the key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run adding this to the registry will launch artillery upon user logon. just to show the process i made a video if you re interested. here is the link https://youtu.be/k7uK9jw7XYY
