### ISSUE TITLE
Running as unprivileged user (non-root)

### ISSUE THREAD

**Issue by jnielsen7** [BinaryDefense/artillery#48]
Curious how you suggest running this as non-root? While a container should work it seems more work than its worth.

Currently I have been attempting to use something along the lines of:
/usr/bin/sandbox -C -H /var/artillery -t sandbox_net_t /var/artillery/artillery.py

But I am still unable to get privileged ports to be accessible even after trying things like:
setcap 'cap_net_bind_service=+ep' /bin/python2.7 

At various levels.

Also I have eliminated SELinux as interfering both by setting to permissive but also disabling silenced avcs.

ie:
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 21. This could be to an active port in use.
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 445. This could be to an active port in use.
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 22. This could be to an active port in use.
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 53. This could be to an active port in use.
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 110. This could be to an active port in use.
Jan 23 10:11:00 hel journal: [!] 2018-01-23 10:11:00: Artillery was unable to bind to port: 135. This could be to an active port in use.

Suggestions?

TIA!

**Comment by trustedsec** [comment]
Socket binding / creations require root unfortunately.
