### ISSUE TITLE
Fileopen1 in SSH_Monitor

### ISSUE THREAD

**Issue by oldkingcone** [BinaryDefense/artillery#51]
[*] An error in ssh monitor occured. Printing it out here: local variable 'fileopen1' referenced before assignment
[*] An error in ssh monitor occured. Printing it out here: local variable 'fileopen1' referenced before assignment
[*] An error in ssh monitor occured. Printing it out here: local variable 'fileopen1' referenced before assignment
 

Error message kept popping up when I would run the artillery main script, was able to solve it by putting an empty variable right after the function for ssh_monitor:

`def ssh_monitor(monitor_frequency):`
`    counter = 0`
`    fileopen1 = ''`
`    while 1:`

**Comment by LevitatingBusinessMan** [comment]
Why is this closed? Seems like a valid issue that should be fixed.
