### ISSUE TITLE
How to change the config for multiple email recipeints 

### ISSUE THREAD

**Issue by hsafe** [BinaryDefense/artillery#64]
Hi,
A quick question and appreciate to clarify if it is possible to add multiple email addresses for the notification. I tried different standard formats and non seems to work here is the patterns I used:
`# THIS IS WHO TO SEND THE ALERTS TO - EMAILS WILL BE SENT FROM ARTILLERY TO THIS ADDRESS
ALERT_USER_EMAIL="mail1,mail2,mail3"

#ALERT_USER_EMAIL="mail1","mail2","mail3"
#`

**Comment by oldkingcone** [comment]
@hsafe It depends on how it is parsed. If it is parsed as a list, then adding brackets around it should work. Otherwise if you are interested in custom configurations, yaml should fill that as a replacement:

`import yaml
mail_list = yaml.safe_load('someconfigfile.yml')
for item in mail_list['Emails']:
     do some stuff here.
`
Example yml file:
`
Email
    - "someemail@somedomain.com"
    - "someotheremail@someotherdomain.com"
`

Hope that helps.

**Comment by hsafe** [comment]
@oldkingcone Thanks for the info...Ill try your suggestion once in the office and update here.
 cheers mate ;)

**Comment by oldkingcone** [comment]
@hsafe Any luck?

**Comment by hsafe** [comment]
No not really :(, you see I tried to stay damn simple with one config file(the default) so that later I manifest it in my puppet-server, so based on what above suggests I tried to put the email list into the recipient stanza with two brackets/curly brackets like:
`# THIS IS WHO TO SEND THE ALERTS TO - EMAILS WILL BE SENT FROM ARTILLERY TO THIS ADDRESS
#ALERT_USER_EMAIL=["email1","email2","email3"]
`
 somehow it does not work :(...oddly enough if I go with the quoted email addresses separated with commas only(earlier pattern) the first email address is hit and its header states other recipients.

**Comment by russhaun** [comment]
hey whats up just throwing this out there. there is actually a file for this in artillery already. look @ config.py
there are functions for dealing with yaml present. i don't think it is enabled look @ file comments it breaks some stuff if enabled.

**Comment by russhaun** [comment]
after looking at this. artillery uses the "ini" format to read in config settings currently. to do what you want a .yml file would need to be provided as @oldkingcone suggested and the current file deleted. you can't have both types present at once. and after that we might still encounter issues with parsing? as other functions are used in that file during startup

**Comment by russhaun** [comment]
edit:
      the option to add cc's can be included in current config file. some pieces of the code will need to be reworked because of py 2 & 3 but it can be done.

**Comment by hsafe** [comment]
Gents, Thanks for taking the time I really appreciate the replies/clarifications here, unfortunately the code change is beyond me :( I need to seek out help from colleagues.
