### ISSUE TITLE
Url error

### ISSUE THREAD

**Issue by Raznak** [BinaryDefense/artillery#7]
Hello, 

there is a error in the setup.py file line 83.
It try to get artillery project from the older repo: 
*subprocess.Popen("git clone https://github.com/trustedsec/artillery /var/artillery/", shell=True).wait()*

update: 
*subprocess.Popen("git clone https://github.com/BinaryDefense/artillery.git /var/artillery/", shell=True).wait()*

**Comment by trustedsec** [comment]
Good call! Thanks for this! Much appreciated and fixed.
